<?php

//function to set crud data for crud query as per request(get/post)
function setCRUDData($data_array)
{
	$data_str = "";
	foreach($data_array as $key=>$value)
	{
		if($data_str == '')
		$data_str .= $key." = '".$value."'";
		else
		$data_str .= ",".$key." = '".$value."'";
	}
	return $data_str;
}

//function to set where cluase for sql as per request(get/post)
function setWhereClause($con_array)
{
	$con_str = " WHERE 1";
	foreach($con_array as $key=>$value)
	{
		$con_str .= " AND ".$key." = '".$value."'";
	}
	return $con_str;
}

//function to set where cluase for sql as per request(get/post)
function setWhereClauseOR($con_array)
{
	$con_str = " WHERE ";
	foreach($con_array as $key=>$value)
	{
		if($con_str == " WHERE ")
		$con_str .= $key." = '".$value."'";
		else
		$con_str .= " OR ".$key." = '".$value."'";
	}
	return $con_str;
}

//function to set where cluase for sql as per request(get/post)
function setWhereClauseAdvance($con_array)
{
	$con_str = " WHERE 1";
	$con_str .= " AND ".implode(' AND ',$con_array);
	return $con_str;
}

//function to get field value on specific condition from specific table
function getFieldValue($getField,$compareField,$compareFieldValue,$table,$con)
{
	$query = "SELECT ".$getField." FROM ".$table." WHERE ".$compareField." = '".$compareFieldValue."'";
	$result = mysqli_query($con, $query);
	$value =  mysqli_fetch_assoc($result);
	return $value[$getField];
}

//function to get field value on specific multi conditions from specific table, $where_clause generated by function setWhererClause
function getFieldValueMultiCon($getField,$where_clause,$table,$con)
{
	$query = "SELECT ".$getField." FROM ".$table.$where_clause;
	$result = mysqli_query($con, $query);
	if(mysqli_num_rows($result))
	{
		$value =  mysqli_fetch_assoc($result);
		return $value[$getField];
	}
}

//function to get sum of a specific column on specific conditions
function getColSumMultiCon($getField,$where_con_array,$table,$con)
{
	$query ="SELECT SUM(".$getField.") AS total FROM ".$table.setWhereClause($where_con_array);
	$result = mysqli_query($con,$query);
	$value = mysqli_fetch_assoc($result);
	return $value['total'];
}

//function to get latest updated field as per specific condition from specific table
function getLatestUpdateWC($getField,$table,$con)
{
	$query = "SELECT DISTINCT ".$getField." FROM ".$table." ORDER BY datentime DESC";
	$result = mysqli_query($con, $query);
	$value =  mysqli_fetch_assoc($result);
	return $value[$getField];
}

//function to get latest updated field as per specific condition from specific table
function getLatestUpdate($getField,$compareField,$compareFieldValue,$table,$con)
{
	$query = "SELECT ".$getField." FROM ".$table." WHERE ".$compareField." = '".$compareFieldValue."' ORDER BY datentime DESC";
	$result = mysqli_query($con, $query);
	$value =  mysqli_fetch_assoc($result);
	return $value[$getField];
}

//function to get latest updated row as per specific condition from specific table
function getLatestUpdateRow($compareField,$compareFieldValue,$table,$con)
{
	$query = "SELECT * FROM ".$table." WHERE ".$compareField." = '".$compareFieldValue."' ORDER BY datentime DESC";
	$result = mysqli_query($con, $query);
	$value =  mysqli_fetch_assoc($result);
	return $value;
}

//function to get row count without any condition from specific table
function getRowCountWC($table,$con)
{
	$query = "SELECT COUNT(*) AS rowcount FROM ".$table;
	$result = mysqli_query($con, $query);
	return mysqli_fetch_assoc($result)['rowcount'];
}

//function to get row count on distinct field on specific condition from specific table
function getRowCountDistinct($distinctField,$compareField,$compareFieldValue,$table,$con)
{
	$query = "SELECT DISTINCT ".$distinctField." FROM ".$table." WHERE ".$compareField." = '".$compareFieldValue."'";
	$result = mysqli_query($con, $query);
	return mysqli_NUM_ROWS($result);
}

//function to get row count on specific condition from specific table
function getRowCount($compareField,$compareFieldValue,$table,$con)
{
	$query = "SELECT COUNT(*) AS rowcount FROM ".$table." WHERE ".$compareField." = '".$compareFieldValue."'";
	$result = mysqli_query($con, $query);
	return mysqli_fetch_assoc($result)['rowcount'];
}

//function to get row count on specific conditions from specific table
function getRowCountMultiCol($where_clause,$table,$con)
{
	$query = "SELECT COUNT(*) AS rowcount FROM ".$table.$where_clause;
	$result = mysqli_query($con, $query);
	return mysqli_fetch_assoc($result)['rowcount'];
}

//function to show eligibility dropdown
function showEligibiltyDropdown($con)
{
	$query_view_min_education_list = "SELECT * FROM min_education_list";
	$result_view_min_education_list = mysqli_query($con, $query_view_min_education_list);

	while($min_education = mysqli_fetch_assoc($result_view_min_education_list))
	{
		$option_list .= "<option value='".$min_education['description']."'>".ucfirst($min_education['description'])."</option>";
	}
	return $option_list;
}

//function to show eligibility dropdown with selected option
function showSelectedEligibiltyDropdown($con,$selected_eligibility)
{
	$query_view_min_education_list = "SELECT * FROM min_education_list";
	$result_view_min_education_list = mysqli_query($con, $query_view_min_education_list);

	while($min_education = mysqli_fetch_assoc($result_view_min_education_list))
	{
		if($min_education['description'] == $selected_eligibility)
		$option_list .= "<option value='".$min_education['description']."' selected='selected'>".ucfirst($min_education['description'])."</option>";
		else
		$option_list .= "<option value='".$min_education['description']."'>".ucfirst($min_education['description'])."</option>";
	}
	return $option_list;
}

//function to display month dropdown
function showMonthsDropdown()
{
	$month_array = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'];
	$option_list = "";

	foreach($month_array as $key)
	{
		$option_list .= "<option value='".$key."'>".strtoupper($key)."</option>";
	}
	return $option_list;
}

//function to display month dropdown with selected month
function showSelectedMonthDropdown($selected_month)
{
	$month_array = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'];
	$option_list = "";

	foreach($month_array as $key)
	{
		if($key == $selected_month)
		$option_list .= "<option value='".$key."' selected='selected'>".strtoupper($key)."</option>";
		else
		$option_list .= "<option value='".$key."'>".strtoupper($key)."</option>";
	}
	return $option_list;
}

//function to display month checkboxes
function showMonthsCheckBoxes($checkbox_name)
{
	$month_array = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'];
	$checkbox_list = "";

	foreach($month_array as $key)
	{
		$checkbox_list .= "<div class='d-flex m-1' style='width:50px;'><input type='checkbox' class='form-check-input ms-1' name='".$checkbox_name."[]' value='".$key."'><span class='ps-1 pe-3'>".strtoupper($key)."</span></option></div>";
	}

	return $checkbox_list;
}

//function to display month checkboxes with selected months
function showSelectedMonthCheckBoxes($checkbox_name,$selected_months_string)
{
	$month_array = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'];
	$checkbox_list = "";

	foreach($month_array as $key)
	{
		if(str_contains($selected_months_string,$key))
		$checkbox_list .= "<div class='d-flex m-1' style='width:50px;'><input type='checkbox' class='form-check-input ms-1' name='".$checkbox_name."[]' value='".$key."' checked><span class='ps-1 pe-3'>".strtoupper($key)."</span></option></div>";
		else
		$checkbox_list .= "<div class='d-flex m-1' style='width:50px;'><input type='checkbox' class='form-check-input ms-1' name='".$checkbox_name."[]' value='".$key."'><span class='ps-1 pe-3'>".strtoupper($key)."</span></option></div>";
	}
	return $checkbox_list;
}

//function to check variable is requested(get/post) or not
function checkIsRequested($requested_var)
{
	if(isset($_REQUEST[$requested_var]) && $_REQUEST[$requested_var])
	return 1;
	else
	return 0;
}

//function to display public portal header
function showPublicPortalHeader($header_title)
{
	echo "<div class='d-flex justify-content-between sticky-top bg-body p-2'>
		<a href='/campusabroad'><img src='../images/ca-logo.png' width='100px'></a>
		<div class='flex-grow-1'>
		<center>
		<h4 class='text-danger-dark mt-2' style='margin-left:30px;'>".$header_title."</h4>
		</center>
		</div>
		</div>";

}

//function to check uniqueness of urn
function checkUniqueURN($urn,$con)
{
	if(getRowCount('urn',$urn,'leads_details',$con))
	{
		checkUniqueURN(rand(100000,999999),$con);
	}
	else
	{
		return $urn;
	}
}

//function unique urn
function createUniqueURN($con)
{
	return checkUniqueURN(rand(100000,999999),$con);
}

//create student login details
function createStudentLogin($con, $student_data)
{
	$query = "INSERT INTO students SET ".setCRUDData($student_data);
	mysqli_query($con, $query);
	return mysqli_insert_id($con);
}

//Insert data in specific table & return last inserted id
function insertData($table,$data_array,$con)
{
	$query = "INSERT INTO ".$table." SET ".setCRUDData($data_array);
	mysqli_query($con, $query);
	return mysqli_insert_id($con);
}

//Update data in specific table on requested condition
function updateData($table,$data_array,$where_con_array,$con)
{
	$query = "UPDATE ".$table." SET ".setCRUDData($data_array).setWhereClause($where_con_array);
	mysqli_query($con, $query);
}

//delete row data in a specific table on requested condition
function deleteData($table,$where_con_array,$con)
{
	$query = "DELETE FROM ".$table.setWhereClause($where_con_array);
	mysqli_query($con, $query);
}

//Retrive data from specific table
function getRowsData($table,$con,$order_by='id',$order='ASC')
{
	$query = "SELECT * FROM ".$table.setOrderByClause($order_by,$order);
	return mysqli_query($con, $query);
}

//Retrive data from specific table on requested condition
function getRowsDataCon($table,$where_con_array,$con,$orderby_clause='')
{
	$query = "SELECT * FROM ".$table.setWhereClause($where_con_array).$orderby_clause;
	return mysqli_query($con, $query);
}

//Retrive data from specific table on requested condition
function getRowsDataConAdvance($table,$where_con_array,$con)
{
	$query = "SELECT * FROM ".$table.setWhereClauseAdvance($where_con_array);
	return mysqli_query($con, $query);
}

//function to set goback url
function setGoBack($goback_url)
{
	echo "<a class='btn btn-sm btn-subtle-warning' href='".$goback_url."'>Go Back</a>";
}

//get latest last batch id
function getMaxBatchId($con)
{
	$query = "SELECT MAX(batch_id) as latest_batch_id FROM lead_status_list";
	$result = mysqli_query($con, $query);
	$batch = mysqli_fetch_assoc($result);
	return $batch['latest_batch_id'];
}

//function set ORDER BY clause
function setOrderByClause($order_by,$order)
{
	return " ORDER BY ".$order_by." ".$order;
}

//function to check course is wishlisted or not by student
function checkWishlisted($course_id, $student_id,$con)
{
	$where_con_array = [ 
						'student_id' => $student_id,
						'course_id' => $course_id,
						];
	return getRowCountMultiCol(setWhereClause($where_con_array),'student_wishlist',$con);
}

//function to get lead count from a specific lead source as per reqested status description
function sourceLeadCount($source_id,$status_description,$con)
{
	$query = "SELECT * FROM leads_details AS LD JOIN lead_status_list AS LSTL ON LD.status_id = LSTL.id WHERE LSTL.description = '".$status_description."' AND LD.source_id = ".$source_id;
	$result = mysqli_query($con, $query);
	return mysqli_num_rows($result);
}

//function to get urn count from a specific application point as per requested status description
function getAPURNCount($application_point_id,$status_description,$con)
{
	$query = "SELECT * FROM leads_details AS LD JOIN lead_status_list AS LSTL ON LD.status_id = LSTL.id WHERE LSTL.description = '".$status_description."' AND LD.application_point_id = ".$application_point_id;
	$result = mysqli_query($con, $query);
	return mysqli_num_rows($result);
}

//function to get urn count from a specific student as per requested status description
function getStudentURNCount($student_id,$status_description,$con)
{
	$query = "SELECT * FROM leads_details AS LD JOIN lead_status_list AS LSTL ON LD.status_id = LSTL.id WHERE LSTL.description = '".$status_description."' AND LD.student_id = ".$student_id;
	$result = mysqli_query($con, $query);
	return mysqli_num_rows($result);
}

//function to get urn count from a specific agent as per requested status description
function getAgentURNCount($agent_id,$status_description,$con)
{
	$query = "SELECT * FROM leads_details AS LD JOIN lead_status_list AS LSTL ON LD.status_id = LSTL.id WHERE LSTL.description = '".$status_description."' AND LD.allocated_id = 'SA".$agent_id."'";
	$result = mysqli_query($con, $query);
	return mysqli_num_rows($result);
}

//function to get urn count from a specific sales person as per requested status description
function getSPURNCount($agent_id,$status_description,$con)
{
	$query = "SELECT * FROM leads_details AS LD JOIN lead_status_list AS LSTL ON LD.status_id = LSTL.id WHERE LSTL.description = '".$status_description."' AND LD.allocated_id = 'SP".$agent_id."'";
	$result = mysqli_query($con, $query);
	return mysqli_num_rows($result);
}

//common function to upload profile picture
function setProfilePic($file,$session_ref_id)
{
	if($file['size'])
	{
		$target_dir = "../profile_pics/";
		$profile_pic_file_extension = pathinfo($file['name'],PATHINFO_EXTENSION);
		$target_file = $target_dir.$session_ref_id.".".$profile_pic_file_extension;
		move_uploaded_file($file["tmp_name"], $target_file);
	}
}

//common function to get profile pic from server profile_pics folder
function getProfilePic($session_ref_id)
{
	if(file_exists("../profile_pics/".$session_ref_id.".jpg"))
	{
		$profile_pic_src = "../profile_pics/".$session_ref_id.".jpg";
	}
	else if(file_exists("../profile_pics/".$session_ref_id.".jpeg"))
	{
		$profile_pic_src = "../profile_pics/".$session_ref_id.".jpeg";
	}
	else
	{
		$profile_pic_src = "../profile_pics/default.png";
	}
	return $profile_pic_src;
}


//function to get latest updated student photo as per specific condition for specific urn/lead
function getLatestURNProfilePic($lead_id,$urn,$con)
{
	$query = "SELECT file_name FROM urn_document_upload_history WHERE lead_id = ".$lead_id." AND file_name LIKE '%student_photo_%' ORDER BY datentime DESC";
	$result = mysqli_query($con, $query);
	if(mysqli_num_rows($result))
	{
		$value =  mysqli_fetch_assoc($result);
		$profile_pic_src = "../urn/ca".$urn."/".$value['file_name'];
	}
	else
	{
		$profile_pic_src = "../profile_pics/default.png";
	}
	return $profile_pic_src;
}

//function to validate login type
function validateLoginType($login_type)
{
	if($login_type)
	echo "hi";
}

//function to create new income record in income history
function createIncomeRecord($lead_id,$con)
{
	$query = "SELECT * FROM leads_details AS LD JOIN course_list AS CL ON LD.course_id = CL.id JOIN application_point_list AS APL ON LD.application_point_id = APL.id WHERE LD.id = ".$lead_id;
	$lead_info = mysqli_fetch_assoc(mysqli_query($con,$query));

	print_r($lead_info);
	echo "<br>";

	$comission_amount = ($lead_info['fee'] * $lead_info['comission_percentage'])/100;

	$income_data = [
					'lead_id' => $lead_id,
					'lead_amount' => $lead_info['fee'],
					'comission_amount' => $comission_amount,
					'comission_rcvd' => 0,
					'application_point_id' => $lead_info['application_point_id'],
					];
	insertData('income_history',$income_data,$con);
	print_r($income_data);
}

//function to create new payment record in comission payment history
function createComissionPaymentRecord($lead_id,$con)
{
	$query = "SELECT * FROM leads_details AS LD JOIN course_list AS CL ON LD.course_id = CL.id JOIN application_point_list AS APL ON LD.application_point_id = APL.id WHERE LD.id = ".$lead_id;
	$lead_info = mysqli_fetch_assoc(mysqli_query($con,$query));

	print_r($lead_info);
	echo "<br>";

	$rcvbl_comission_amount = ($lead_info['fee'] * $lead_info['comission_percentage'])/100;

	if($lead_info['allocated_id'] != 0)
	{
		if(substr($lead_info['allocated_id'],0,2) == 'SA')
			$comission_percetage = getFieldValue('comission','id',substr($lead_info['allocated_id'],2),'agent_list',$con);
		else if(substr($lead_info['allocated_id'],0,2) == 'SP')
			$comission_percetage = getFieldValue('comission','id',substr($lead_info['allocated_id'],2),'sales_person_list',$con);

		$payable_comission_amount = ($rcvbl_comission_amount * $comission_percetage)/100;

		$comission_payment_data = [
						'lead_id' => $lead_id,
						'lead_amount' => $lead_info['fee'],
						'comission_amount' => $payable_comission_amount,
						'comission_paid' => 0,
						'comission_paid_to' => $lead_info['allocated_id'],
						];
		insertData('comission_paid_history',$comission_payment_data,$con);
		print_r($comission_payment_data);
	}
}

?>