<?php

//function to set crud data for crud query as per request(get/post)
function setCRUDData($data_array)
{
	$data_str = "";
	foreach($data_array as $key=>$value)
	{
		if($data_str == '')
		$data_str .= $key." = '".$value."'";
		else
		$data_str .= ",".$key." = '".$value."'";
	}
	return $data_str;
}

//function to set where cluase for sql as per request(get/post)
function setWhereClause($con_array)
{
	$con_str = " WHERE 1";
	foreach($con_array as $key=>$value)
	{
		$con_str .= " AND ".$key." = '".$value."'";
	}
	return $con_str;
}

//function to set where cluase for sql as per request(get/post)
function setWhereClauseOR($con_array)
{
	$con_str = " WHERE ";
	foreach($con_array as $key=>$value)
	{
		if($con_str == " WHERE ")
		$con_str .= $key." = '".$value."'";
		else
		$con_str .= " OR ".$key." = '".$value."'";
	}
	return $con_str;
}

//function to set where cluase for sql as per request(get/post)
function setWhereClauseAdvance($con_array)
{
	$con_str = " WHERE 1";
	$con_str .= " AND ".implode(' AND ',$con_array);
	return $con_str;
}

//function to get field value on specific condition from specific table
function getFieldValue($getField,$compareField,$compareFieldValue,$table,$con)
{
	$query = "SELECT ".$getField." FROM ".$table." WHERE ".$compareField." = '".$compareFieldValue."'";
	$result = mysqli_query($con, $query);
	$value =  mysqli_fetch_assoc($result);
	return $value[$getField];
}

//function to get field value on specific multi conditions from specific table, $where_clause generated by function setWhererClause
function getFieldValueMultiCon($getField,$where_clause,$table,$con)
{
	$query = "SELECT ".$getField." FROM ".$table.$where_clause;
	$result = mysqli_query($con, $query);
	if(mysqli_num_rows($result))
	{
		$value =  mysqli_fetch_assoc($result);
		return $value[$getField];
	}
}

//function to get sum of a specific column on specific conditions
function getColSumMultiCon($getField,$where_con_array,$table,$con)
{
	$query ="SELECT SUM(".$getField.") AS total FROM ".$table.setWhereClause($where_con_array);
	$result = mysqli_query($con,$query);
	$value = mysqli_fetch_assoc($result);
	return $value['total'];
}

//function to get latest updated field as per specific condition from specific table
function getLatestUpdateWC($getField,$table,$con)
{
	$query = "SELECT DISTINCT ".$getField." FROM ".$table." ORDER BY datentime DESC";
	$result = mysqli_query($con, $query);
	$value =  mysqli_fetch_assoc($result);
	return $value[$getField];
}

//function to get latest updated field as per specific condition from specific table
function getLatestUpdate($getField,$compareField,$compareFieldValue,$table,$con)
{
	$query = "SELECT ".$getField." FROM ".$table." WHERE ".$compareField." = '".$compareFieldValue."' ORDER BY datentime DESC";
	$result = mysqli_query($con, $query);
	$value =  mysqli_fetch_assoc($result);
	return $value[$getField];
}

//function to get latest updated row as per specific condition from specific table
function getLatestUpdateRow($compareField,$compareFieldValue,$table,$con)
{
	$query = "SELECT * FROM ".$table." WHERE ".$compareField." = '".$compareFieldValue."' ORDER BY datentime DESC";
	$result = mysqli_query($con, $query);
	$value =  mysqli_fetch_assoc($result);
	return $value;
}

//function to get row count without any condition from specific table
function getRowCountWC($table,$con)
{
	$query = "SELECT COUNT(*) AS rowcount FROM ".$table;
	$result = mysqli_query($con, $query);
	return mysqli_fetch_assoc($result)['rowcount'];
}

//function to get row count on distinct field on specific condition from specific table
function getRowCountDistinct($distinctField,$compareField,$compareFieldValue,$table,$con)
{
	$query = "SELECT DISTINCT ".$distinctField." FROM ".$table." WHERE ".$compareField." = '".$compareFieldValue."'";
	$result = mysqli_query($con, $query);
	return mysqli_NUM_ROWS($result);
}

//function to get row count on specific condition from specific table
function getRowCount($compareField,$compareFieldValue,$table,$con)
{
	$query = "SELECT COUNT(*) AS rowcount FROM ".$table." WHERE ".$compareField." = '".$compareFieldValue."'";
	$result = mysqli_query($con, $query);
	return mysqli_fetch_assoc($result)['rowcount'];
}

//function to get row count on specific conditions from specific table
function getRowCountMultiCol($where_clause,$table,$con)
{
	$query = "SELECT COUNT(*) AS rowcount FROM ".$table.$where_clause;
	$result = mysqli_query($con, $query);
	return mysqli_fetch_assoc($result)['rowcount'];
}

//function to show eligibility dropdown
function showEligibiltyDropdown($con)
{
	$query_view_min_education_list = "SELECT * FROM min_education_list";
	$result_view_min_education_list = mysqli_query($con, $query_view_min_education_list);

	while($min_education = mysqli_fetch_assoc($result_view_min_education_list))
	{
		$option_list .= "<option value='".$min_education['description']."'>".ucfirst($min_education['description'])."</option>";
	}
	return $option_list;
}

//function to show eligibility dropdown with selected option
function showSelectedEligibiltyDropdown($con,$selected_eligibility)
{
	$query_view_min_education_list = "SELECT * FROM min_education_list";
	$result_view_min_education_list = mysqli_query($con, $query_view_min_education_list);

	while($min_education = mysqli_fetch_assoc($result_view_min_education_list))
	{
		if($min_education['description'] == $selected_eligibility)
		$option_list .= "<option value='".$min_education['description']."' selected='selected'>".ucfirst($min_education['description'])."</option>";
		else
		$option_list .= "<option value='".$min_education['description']."'>".ucfirst($min_education['description'])."</option>";
	}
	return $option_list;
}

//function to display month dropdown
function showMonthsDropdown()
{
	$month_array = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'];
	$option_list = "";

	foreach($month_array as $key)
	{
		$option_list .= "<option value='".$key."'>".strtoupper($key)."</option>";
	}
	return $option_list;
}

//function to display month dropdown with selected month
function showSelectedMonthDropdown($selected_month)
{
	$month_array = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'];
	$option_list = "";

	foreach($month_array as $key)
	{
		if($key == $selected_month)
		$option_list .= "<option value='".$key."' selected='selected'>".strtoupper($key)."</option>";
		else
		$option_list .= "<option value='".$key."'>".strtoupper($key)."</option>";
	}
	return $option_list;
}

//function to display month checkboxes
function showMonthsCheckBoxes($checkbox_name)
{
	$month_array = ['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'];
	$checkbox_list = "";

	foreach($month_array as $key)
	{
		$checkbox_list .= "<div class='d-flex m-1' style='width:50px;'><input type='checkbox' class='form-check-input ms-1' name='".$checkbox_name."[]' value='".$key."'><span class='ps-1 pe-3'>".$key."</span></option></div>";
	}

	return $checkbox_list;
}

//function to display month checkboxes with selected months
function showSelectedMonthCheckBoxes($checkbox_name,$selected_months_string)
{
	$month_array = ['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'];
	$checkbox_list = "";

	foreach($month_array as $key)
	{
		if(str_contains($selected_months_string,$key))
		$checkbox_list .= "<div class='d-flex m-1' style='width:50px;'><input type='checkbox' class='form-check-input ms-1' name='".$checkbox_name."[]' value='".$key."' checked><span class='ps-1 pe-3'>".$key."</span></option></div>";
		else
		$checkbox_list .= "<div class='d-flex m-1' style='width:50px;'><input type='checkbox' class='form-check-input ms-1' name='".$checkbox_name."[]' value='".$key."'><span class='ps-1 pe-3'>".$key."</span></option></div>";
	}
	return $checkbox_list;
}

//function to check variable is requested(get/post) or not
function checkIsRequested($requested_var)
{
	if(isset($_REQUEST[$requested_var]) && $_REQUEST[$requested_var])
	return 1;
	else
	return 0;
}

//function to display public portal header
function showPublicPortalHeader($header_title)
{
	echo "<div class='d-flex justify-content-between sticky-top bg-body p-2'>
		<a href='/campusabroad'><img src='../images/ca-logo.png' width='100px'></a>
		<div class='flex-grow-1'>
		<center>
		<h4 class='text-danger-dark mt-2' style='margin-left:30px;'>".$header_title."</h4>
		</center>
		</div>
		</div>";

}

//function to check uniqueness of urn
function checkUniqueURN($urn,$con)
{
	if(getRowCount('urn',$urn,'leads_details',$con))
	{
		checkUniqueURN(rand(100000,999999),$con);
	}
	else
	{
		return $urn;
	}
}

//function unique urn
function createUniqueURN($con)
{
	return checkUniqueURN(rand(100000,999999),$con);
}

//create student login details
function createStudentLogin($con, $student_data)
{
	$query = "INSERT INTO students SET ".setCRUDData($student_data);
	mysqli_query($con, $query);
	return mysqli_insert_id($con);
}

//Insert data in specific table & return last inserted id
function insertData($table,$data_array,$con)
{
	$query = "INSERT INTO ".$table." SET ".setCRUDData($data_array);
	mysqli_query($con, $query);
	return mysqli_insert_id($con);
}

//Update data in specific table on requested condition
function updateData($table,$data_array,$where_con_array,$con)
{
	$query = "UPDATE ".$table." SET ".setCRUDData($data_array).setWhereClause($where_con_array);
	mysqli_query($con, $query);
}

//delete row data in a specific table on requested condition
function deleteData($table,$where_con_array,$con)
{
	$query = "DELETE FROM ".$table.setWhereClause($where_con_array);
	mysqli_query($con, $query);
}

//Retrive data from specific table
function getRowsData($table,$con,$order_by='id',$order='ASC')
{
	$query = "SELECT * FROM ".$table.setOrderByClause($order_by,$order);
	return mysqli_query($con, $query);
}

//Retrive data from specific table on requested condition
function getRowsDataCon($table,$where_con_array,$con,$orderby_clause='')
{
	$query = "SELECT * FROM ".$table.setWhereClause($where_con_array).$orderby_clause;
	return mysqli_query($con, $query);
}

//Retrive data from specific table on requested condition
function getRowsDataConAdvance($table,$where_con_array,$con,$orderby_clause='')
{
	$query = "SELECT * FROM ".$table.setWhereClauseAdvance($where_con_array).$orderby_clause;
	return mysqli_query($con, $query);
}

//function to set goback url
function setGoBack($goback_url)
{
	//echo "<a class='btn btn-sm btn-subtle-warning' href='".$goback_url."'>Go Back</a>";
	echo "<button class='btn btn-sm btn-subtle-warning' onclick='history.back()'>Go Back</button>";
}

//get latest last batch id
function getMaxBatchId($con)
{
	$query = "SELECT MAX(batch_id) as latest_batch_id FROM lead_status_list";
	$result = mysqli_query($con, $query);
	$batch = mysqli_fetch_assoc($result);
	return $batch['latest_batch_id'];
}

//function set ORDER BY clause
function setOrderByClause($order_by,$order)
{
	return " ORDER BY ".$order_by." ".$order;
}

//function to check course is wishlisted or not by student
function checkWishlisted($course_id, $student_id,$con)
{
	$where_con_array = [ 
						'student_id' => $student_id,
						'course_id' => $course_id,
						];
	return getRowCountMultiCol(setWhereClause($where_con_array),'student_wishlist',$con);
}

//function to get lead count from a specific lead source as per reqested status description
function sourceLeadCount($source_id,$status_description,$con)
{
	$query = "SELECT * FROM leads_details AS LD JOIN lead_status_list AS LSTL ON LD.status_id = LSTL.id WHERE LSTL.description = '".$status_description."' AND LD.source_id = ".$source_id;
	$result = mysqli_query($con, $query);
	return mysqli_num_rows($result);
}

//function to get urn count from a specific application point as per requested status description
function getAPURNCount($application_point_id,$status_description,$con)
{
	$query = "SELECT * FROM leads_details AS LD JOIN lead_status_list AS LSTL ON LD.status_id = LSTL.id WHERE LSTL.description = '".$status_description."' AND LD.application_point_id = ".$application_point_id;
	$result = mysqli_query($con, $query);
	return mysqli_num_rows($result);
}

//function to get urn count from a specific student as per requested status description
function getStudentURNCount($student_id,$status_description,$con)
{
	$query = "SELECT * FROM leads_details AS LD JOIN lead_status_list AS LSTL ON LD.status_id = LSTL.id WHERE LSTL.description = '".$status_description."' AND LD.student_id = ".$student_id;
	$result = mysqli_query($con, $query);
	return mysqli_num_rows($result);
}

//function to get urn count from a specific agent as per requested status description
function getAgentURNCount($agent_id,$status_description,$con)
{
	$query = "SELECT * FROM leads_details AS LD JOIN lead_status_list AS LSTL ON LD.status_id = LSTL.id WHERE LSTL.description = '".$status_description."' AND LD.allocated_id = 'SA".$agent_id."'";
	$result = mysqli_query($con, $query);
	return mysqli_num_rows($result);
}

//function to get urn count from a specific sales person as per requested status description
function getSPURNCount($agent_id,$status_description,$con)
{
	$query = "SELECT * FROM leads_details AS LD JOIN lead_status_list AS LSTL ON LD.status_id = LSTL.id WHERE LSTL.description = '".$status_description."' AND LD.allocated_id = 'SP".$agent_id."'";
	$result = mysqli_query($con, $query);
	return mysqli_num_rows($result);
}

//common function to upload profile picture
function setProfilePic($file,$session_ref_id)
{
	if($file['size'])
	{
		$target_dir = "../profile_pics/";
		$profile_pic_file_extension = pathinfo($file['name'],PATHINFO_EXTENSION);
		$target_file = $target_dir.$session_ref_id.".".$profile_pic_file_extension;
		move_uploaded_file($file["tmp_name"], $target_file);
	}
}

//common function to get profile pic from server profile_pics folder
function getProfilePic($session_ref_id)
{
	if(file_exists("../profile_pics/".$session_ref_id.".jpg"))
	{
		$profile_pic_src = "../profile_pics/".$session_ref_id.".jpg";
	}
	else if(file_exists("../profile_pics/".$session_ref_id.".jpeg"))
	{
		$profile_pic_src = "../profile_pics/".$session_ref_id.".jpeg";
	}
	else
	{
		$profile_pic_src = "../profile_pics/default.png";
	}
	return $profile_pic_src;
}


//function to get latest updated student photo as per specific condition for specific urn/lead
function getLatestURNProfilePic($lead_id,$urn,$con)
{
	$query = "SELECT file_name FROM urn_document_upload_history WHERE lead_id = ".$lead_id." AND file_name LIKE '%student_photo_%' ORDER BY datentime DESC";
	$result = mysqli_query($con, $query);
	if(mysqli_num_rows($result))
	{
		$value =  mysqli_fetch_assoc($result);
		$profile_pic_src = "../urn/ca".$urn."/".$value['file_name'];
	}
	else
	{
		$profile_pic_src = "../profile_pics/default.png";
	}
	return $profile_pic_src;
}

//function to create new income record in income history
function createIncomeRecord($lead_id,$con)
{
	$query = "SELECT * FROM leads_details AS LD JOIN course_list AS CL ON LD.course_id = CL.id JOIN application_point_list AS APL ON LD.application_point_id = APL.id WHERE LD.id = ".$lead_id;
	$lead_info = mysqli_fetch_assoc(mysqli_query($con,$query));

	print_r($lead_info);
	echo "<br>";

	$comission_amount = ($lead_info['fee'] * $lead_info['comission_percentage'])/100;

	$income_data = [
					'lead_id' => $lead_id,
					'lead_amount' => $lead_info['fee'],
					'comission_amount' => $comission_amount,
					'comission_rcvd' => 0,
					'application_point_id' => $lead_info['application_point_id'],
					];
	insertData('income_history',$income_data,$con);
	print_r($income_data);
}

//function to create new payment record in comission payment history
function createComissionPaymentRecord($lead_id,$con)
{
	$query = "SELECT * FROM leads_details AS LD JOIN course_list AS CL ON LD.course_id = CL.id JOIN application_point_list AS APL ON LD.application_point_id = APL.id WHERE LD.id = ".$lead_id;
	$lead_info = mysqli_fetch_assoc(mysqli_query($con,$query));

	print_r($lead_info);
	echo "<br>";

	$rcvbl_comission_amount = ($lead_info['fee'] * $lead_info['comission_percentage'])/100;

	if($lead_info['allocated_id'] != 0)
	{
		if(substr($lead_info['allocated_id'],0,2) == 'SA')
			$comission_percetage = getFieldValue('comission','id',substr($lead_info['allocated_id'],2),'agent_list',$con);
		else if(substr($lead_info['allocated_id'],0,2) == 'SP')
			$comission_percetage = getFieldValue('comission','id',substr($lead_info['allocated_id'],2),'sales_person_list',$con);

		$payable_comission_amount = ($rcvbl_comission_amount * $comission_percetage)/100;

		$comission_payment_data = [
						'lead_id' => $lead_id,
						'lead_amount' => $lead_info['fee'],
						'comission_amount' => $payable_comission_amount,
						'comission_paid' => 0,
						'comission_paid_to' => $lead_info['allocated_id'],
						];
		insertData('comission_paid_history',$comission_payment_data,$con);
		print_r($comission_payment_data);
	}
}

//function to validate login_type for access restriction
function validateLoginType($login_type)
{
	if($login_type != 1 && $login_type != 8 && $login_type != 7)
	{
		header("Location:dashboard.php");
		die();
	}
}

//function to check login_type
function checkLoginType($login_type)
{
	if($login_type != 1 && $login_type != 8 && $login_type != 7)
	{
		return 0;
	}
	else 
	{
		return 1;
	}
}

//function to show authorization menu options
function showAuthorizationOption($con)
{
	$authorized_submenu_options_array = [1,2,23];
	$where_con_array = [ 'parent_menu_id' => 1];
	$menu_item_list = getRowsDataCon('menu_items',$where_con_array,$con);
	$default_menu_items = [1,2,6];
	$restricted_menu_items = [9];
	$autorised_menu_items = "";

	while($menu_item = mysqli_fetch_assoc($menu_item_list))
	{
		if(in_array($menu_item['id'],$default_menu_items))
		{
			$autorised_menu_items .= "<div class='card m-1 p-2' style='width:250px;'><div><input type='checkbox' class='form-input-check m-1 d-none' name='authorised_menu[]' value='".$menu_item['id']."' checked><span class='text-primary m-1' data-feather='check-square' style='height: 15px; width: 15px;'></span>".$menu_item['description']."</div>";
			$autorised_menu_items .= showAuthorizedSubMenuOptions($menu_item['id'],$authorized_submenu_options_array,$con);
			$autorised_menu_items .= "</div>";
		}
		else if(!in_array($menu_item['id'],$default_menu_items) && !in_array($menu_item['id'],$restricted_menu_items))
		{
			$autorised_menu_items .= "<div class='card m-1 p-2' style='width:250px;'><div><input type='checkbox' id='menuitem_".$menu_item['id']."' onClick='setSubmenuItems(".$menu_item['id'].",this.checked)' class='form-input-check m-1 bg-danger' name='authorised_menu[]' value='".$menu_item['id']."'>".$menu_item['description']."</div>";
			$autorised_menu_items .= showAuthorizedSubMenuOptions($menu_item['id'],$authorized_submenu_options_array,$con);
			$autorised_menu_items .= "</div>";
		}
	}
	echo $autorised_menu_items;
}

//function to show authorized menu options
function showAuthorizedMenuOptions($con,$staff_id)
{
	$authorized_menu_options = getFieldValue('authorised_menu_options','id',$staff_id,'staff_list',$con);
	$authorized_menu_options_array = explode(',',$authorized_menu_options);

	$authorized_submenu_options = getFieldValue('authorised_submenu_options','id',$staff_id,'staff_list',$con);
	$authorized_submenu_options_array = explode(',',$authorized_submenu_options);

	$where_con_array = [ 'parent_menu_id' => 1];
	$menu_item_list = getRowsDataCon('menu_items',$where_con_array,$con);
	$default_menu_items = [1,2,6];
	$restricted_menu_items = [9];
	$autorised_menu_items = "";

	while($menu_item = mysqli_fetch_assoc($menu_item_list))
	{
		if(in_array($menu_item['id'],$default_menu_items))
		{
			$autorised_menu_items .= "<div class='card m-1 p-2' style='width:250px;'><div><input type='checkbox' class='form-input-check m-1 d-none' name='authorised_menu[]' value='".$menu_item['id']."' checked><span class='text-primary m-1' data-feather='check-square' style='height: 15px; width: 15px;'></span>".$menu_item['description']."</div>";
			$autorised_menu_items .= showAuthorizedSubMenuOptions($menu_item['id'],$authorized_submenu_options_array,$con);			
			$autorised_menu_items .= "</div>";
		}
		else if(in_array($menu_item['id'],$authorized_menu_options_array))
		{
			$autorised_menu_items .= "<div class='card m-1 p-2' style='width:250px;'><div><input type='checkbox' id='menuitem_".$menu_item['id']."' onClick='setSubmenuItems(".$menu_item['id'].",this.checked)' class='form-input-check m-1 bg-danger' name='authorised_menu[]' value='".$menu_item['id']."' checked>".$menu_item['description']."</div>";
			$autorised_menu_items .= showAuthorizedSubMenuOptions($menu_item['id'],$authorized_submenu_options_array,$con);			
			$autorised_menu_items .= "</div>";
		}
		else if(!in_array($menu_item['id'],$default_menu_items) && !in_array($menu_item['id'],$restricted_menu_items))
		{
			$autorised_menu_items .= "<div class='card m-1 p-2' style='width:250px;'><div><input type='checkbox' id='menuitem_".$menu_item['id']."' onClick='setSubmenuItems(".$menu_item['id'].",this.checked)' class='form-input-check m-1 bg-danger' name='authorised_menu[]' value='".$menu_item['id']."'>".$menu_item['description']."</div>";
			$autorised_menu_items .= showAuthorizedSubMenuOptions($menu_item['id'],$authorized_submenu_options_array,$con);			
			$autorised_menu_items .= "</div>";
		}
	}
	echo $autorised_menu_items;
}

//function to get authorize submenu option for specific menu item
function showAuthorizedSubMenuOptions($menu_item_id,$authorized_submenu_options_array,$con)
{
	$autorised_submenu_items = "";
	$where_con_array = ['parent_menu_item_id' => $menu_item_id];
	$submenu_item_list = getRowsDataCon('submenu_items',$where_con_array,$con);
	//total submenu items count for request parent menu item id
	$total_submenu_item = getRowCount('parent_menu_item_id',$menu_item_id,'submenu_items',$con);
	$selected_submenu_count = 0;
	$i = 0;
	while($submenu_item = mysqli_fetch_assoc($submenu_item_list))
	{
		$i++;
		if(in_array($submenu_item['id'],$authorized_submenu_options_array))
		{
			$autorised_submenu_items .= "<div class='ps-3'><input type='checkbox' id='submenu_$menu_item_id"."_"."$i' onClick='setMenuItem(".$menu_item_id.",this.checked)' class='form-input-check m-1' name='authorised_submenu[]' value='".$submenu_item['id']."' checked>".$submenu_item['description']."</div>";
			$selected_submenu_count++;
		}
		else
		$autorised_submenu_items .= "<div class='ps-3'><input type='checkbox' id='submenu_$menu_item_id"."_"."$i' onClick='setMenuItem(".$menu_item_id.",this.checked)' class='form-input-check m-1' name='authorised_submenu[]' value='".$submenu_item['id']."'>".$submenu_item['description']."</div>";
	}

	$autorised_submenu_items .= "<input type='hidden' id='submenu_count_$menu_item_id' value='$total_submenu_item'><input type='hidden' id='selected_submenu_count_$menu_item_id' value='$selected_submenu_count'>";

	return $autorised_submenu_items;
}

//function to generate submenu items dynamicaly as per login_type
function generateSubmenu($con,$parent_menu_item_id)
{
	if($_SESSION['user_table'] == 'staff_list')
	{
		$authorized_submenu_options = getFieldValue('authorised_submenu_options','id',$_SESSION['userid'],$_SESSION['user_table'],$con);
		$authorized_submenu_options_array = explode(',',$authorized_submenu_options);
	}
	else
	{
		$authorized_submenu_options_array = [];
		$query = "SELECT id FROM submenu_items WHERE parent_menu_item_id = $parent_menu_item_id";
		$submenu_items = mysqli_query($con,$query);
		while($submenu_item = mysqli_fetch_assoc($submenu_items))
		{
			array_push($authorized_submenu_options_array,$submenu_item['id']);
		}
	}

	$where_con_array = [ 'parent_menu_item_id' => $parent_menu_item_id, ];
    $submenu_item_list = getRowsDataCon('submenu_items',$where_con_array,$con);
    $submenu_items = "";
    while($submenu_item = mysqli_fetch_assoc($submenu_item_list))
    {
		if($_SESSION['login_type'] != 7)
		{
			if(in_array($submenu_item['id'],$authorized_submenu_options_array))
			$submenu_items .= "<li class='nav-item'><a class='nav-link' href='".$submenu_item['href_link']."'>
									<div class='d-flex align-items-center'><span class='nav-link-text'>".$submenu_item['description']."</span>
									</div>
								</a>
								<!-- more inner pages-->
								</li>";
		}
		else
		{
			$submenu_items .= "<li class='nav-item'><a class='nav-link' href='".$submenu_item['href_link']."'>
									<div class='d-flex align-items-center'><span class='nav-link-text'>".$submenu_item['description']."</span>
									</div>
								</a>
								<!-- more inner pages-->
								</li>";
		}
    }
	return $submenu_items;
}

//function to generate dynamic sidebar menu
function generateSidebarMenu($con)
{
	$where_con_array = [ 'parent_menu_id' => $_SESSION['menu_id'],];
	$authorized_menu_options = "";

	if($_SESSION['user_table'] == 'staff_list' && $_SESSION['login_type'] != 7)
	$authorized_menu_options .= getFieldValue('authorised_menu_options','id',$_SESSION['userid'],$_SESSION['user_table'],$con);
	else
	{
		//create authorised_menu_options as per menu items available in specific menu
		$default_menu_items = getRowsDataCon('menu_items',$where_con_array,$con);
		while($default_menu_item = mysqli_fetch_assoc($default_menu_items))
		{
			$authorized_menu_options .= $default_menu_item['id'].",";
		}
	}

	$authorized_menu_options_array = explode(',',$authorized_menu_options);

    $menu_item_list = getRowsDataCon('menu_items',$where_con_array,$con);
    while($menu_item = mysqli_fetch_assoc($menu_item_list))
    {
        if(in_array($menu_item['id'],$authorized_menu_options_array))
        {
			if($menu_item['description'] == 'URN Management')
			$submenu_items = generateLeadManagementMenuItems($con);
			else
			$submenu_items = generateSubmenu($con,$menu_item['id']);

            echo "<div class='nav-item-wrapper'>
                    <a class='nav-link dropdown-indicator label-1' href='#nv-".$menu_item['submenu_id_name']."' role='button' data-bs-toggle='collapse' aria-expanded='false' aria-controls='nv-".$menu_item['submenu_id_name']."'>
                        <div class='d-flex align-items-center'>
                            <div class='dropdown-indicator-icon-wrapper'><span class='fas fa-caret-right dropdown-indicator-icon'></span></div><span class='nav-link-icon'><span data-feather='".$menu_item['icon_name']."'></span></span><span class='nav-link-text'>".$menu_item['description']."</span>
                        </div>
                    </a>
                    <div class='parent-wrapper label-1'>
                    <ul class='nav collapse parent' data-bs-parent='#navbarVerticalCollapse' id='nv-".$menu_item['submenu_id_name']."'>
                        ".$submenu_items."
                    </ul>
                    </div>
                </div>";
        }
    }
}

//function to generate lead_management_menu_items as per all lead status
function generateLeadManagementMenuItems($con)
{
	if(substr($_SESSION['user_ref_id'],0,2) == 'SA' || substr($_SESSION['user_ref_id'],0,2) == 'SP')
	$all_leads_for_current_user = getRowCount('allocated_id',$_SESSION['user_ref_id'],'leads_details',$con);
	else
	$all_leads_for_current_user = getRowCountWC('leads_details',$con);

	$lead_management_menu_items = "<li class='nav-item'><a class='nav-link' href='leads.php'><div class='d-flex align-items-center'><span class='nav-link-text'>All (".$all_leads_for_current_user.")</span></div></a></li>";
	$allocated_where_con = "";
	
	if(substr($_SESSION['user_ref_id'],0,2) == 'SA' || substr($_SESSION['user_ref_id'],0,2) == 'SP')
	$allocated_where_con .= " AND ld.allocated_id = '".$_SESSION['user_ref_id']."'";

	$query_view_lead_status_list = "SELECT DISTINCT description FROM lead_status_list";
	$result_view_lead_status_list = mysqli_query($con, $query_view_lead_status_list);
	while($status = mysqli_fetch_assoc($result_view_lead_status_list))
	{
        //get total lead count as per status description
        $query_total_leads_per_status = "SELECT * FROM leads_details AS ld JOIN lead_status_list AS lsl ON ld.status_id = lsl.id WHERE lsl.description = '".$status['description']."'".$allocated_where_con;
        $result_total_leads_per_status = mysqli_query($con,$query_total_leads_per_status);
        $leads_counter = mysqli_num_rows($result_total_leads_per_status);

		$lead_management_menu_items .= "<li class='nav-item'><a class='nav-link' href='leads.php?status=".$status['description']."'><span class='nav-link-text'>".$status['description']." <span class='text-danger'>(".$leads_counter.")</span></span></a></li>";
	}
	return $lead_management_menu_items;
}

//function to create menu list dropdown
function generateMenuListDropdown($con)
{
	$menu_dropdown =  "<select name='parent_menu_id' id='parent_menu_id' class='form-select form-select-sm m-1' style='width:200px;' required>
	<option value=''>Select Parent Menu</option>";

	$menu_list = getRowsData('menu_list',$con);
	while($menu = mysqli_fetch_assoc($menu_list))
	{
		$menu_dropdown .= "<option value='".$menu['id']."'>".$menu['description']."</option>";
	}

	$menu_dropdown .= "</select>";

	return $menu_dropdown;
}

//function to create menu list dropdown with selected menu for specific menu item
function generateSelectedMenuListDropdown($con,$parent_menu_id)
{
	$menu_dropdown =  "<select name='parent_menu_id' class='form-select form-select-sm m-1' style='width:200px;' required>
	<option value=''>Select Parent Menu</option>";

	$menu_list = getRowsData('menu_list',$con);
	while($menu = mysqli_fetch_assoc($menu_list))
	{
		if($menu['id'] == $parent_menu_id)
		$menu_dropdown .= "<option value='".$menu['id']."' selected>".$menu['description']."</option>";
		else
		$menu_dropdown .= "<option value='".$menu['id']."'>".$menu['description']."</option>";
	}

	$menu_dropdown .= "</select>";

	return $menu_dropdown;
}

//function to get current week start day as timestamp
function getWeekStart()
{
	if(date('l',strtotime('now')) == 'Monday')
		return strtotime("today");
	else
		return strtotime("Last Monday");
}

//function to get current week end day as timestamp
function getWeekEnd()
{
	if(date('l',strtotime('now')) == 'Sunday')
		return strtotime('tomorrow');
	else
		return strtotime("Next Monday");
}

//function to get table name as per input user_ref_id
function getTablename($ref_id)
{
	if(substr($ref_id,0,2) == 'BS')
		$table_name = 'staff_list' ;
	else if(substr($ref_id,0,2) == 'SA')
		$table_name = 'agent_list' ;
	if(substr($ref_id,0,2) == 'SP')
		$table_name = 'sales_person_list' ;
	if(substr($ref_id,0,2) == 'ST')
		$table_name = 'students' ;

	return $table_name;
}

//function to generate year list dropdrown, it takes start year as input
function generateYearDropdown($start,$yearSelected = '')
{
	$option = "";
	$current_year = date('Y',strtotime('now'));
	for($i=$start;$i<=$current_year;$i++)
	{
		if($i == $yearSelected)
		$option .= "<option value='".$i."' selected>".$i."</option>";
		else
		$option .= "<option value='".$i."'>".$i."</option>";
	}
	return $option;
}

//function to make dropdown option selected as per input
function setOptionSelected($optionValue,$selectedValue)
{
	if($optionValue == $selectedValue)
	return "selected";
}

//function to uploadAcademicDocuments
function uploadAcademicDocuments($inputFile,$lead_id,$con)
{
	//get urn for requested lead_id
	$urn = getFieldValue('urn','id',$_REQUEST['lead_id'],'leads_details',$con);

	//urn folder path
	$target_folder = "../urn/ca".$urn."/academic";

	//check whether urn/academic folder exist or not; if not then create urn folder with full permission
	if (!file_exists($target_folder)) 
	{
		mkdir($target_folder, 0777, true);
	}

	//allowed file extensions
	$file_extension_array = ['.jpg','.jpeg','.pdf'];
	//$date_identifier = date("YmdHis");
	$date_identifier = strtotime('now');

	$inputFile = $_FILES;
	count($inputFile);

	foreach($inputFile as $key => $value)
	{
		if(!str_contains($key,'other_test_proof') && $value['size'] > 0)
		{
			$newfilename = $key.'_'.$date_identifier.'.'.pathinfo($value['name'], PATHINFO_EXTENSION);
			move_uploaded_file($value['tmp_name'], $target_folder."/".$newfilename);
			createDocumentUploadHistory($lead_id,$urn,"academic/".$newfilename,$con);
		}
		else if(str_contains($key,'other_test_proof') && count($value['name']) > 0)
		{
			for($i=0;$i<count($value['name']);$i++)
			{
				if($value['size'][$i] > 0)
				{
					$newfilename = $_REQUEST['other_test_name'][$i].'_'.$date_identifier.'.'.pathinfo($value['name'][$i], PATHINFO_EXTENSION);
					move_uploaded_file($value['tmp_name'][$i], $target_folder."/".$newfilename);
					createDocumentUploadHistory($lead_id,$urn,"academic/".$newfilename,$con);
				}
			}
		}

	}
}

//function to create document upload history
function createDocumentUploadHistory($lead_id,$urn,$uploded_file_name,$con)
{
	//insert into urn_document_upload_history
	$document_upload_info = [
								'lead_id' => $lead_id,
								'urn' => $urn,
								'file_name' => $uploded_file_name,
								'datentime' => strtotime('now'),
								'upload_by' => $_SESSION['user_ref_id'],
							];
				
	insertData('urn_document_upload_history', $document_upload_info, $con);
}

//function to add default menu item Dashboard in sidebar menu in project
function addMenuItemDashboard()
{
	return "<div class='nav-item-wrapper'>
            <a class='nav-link dropdown-indicator label-1' href='dashboard.php'>
                <div class='d-flex align-items-center'>
                    <div class='dropdown-indicator-icon-wrapper'>
                    <span class='fas fa-caret-right dropdown-indicator-icon'></span>
                    </div>
                    <span class='nav-link-icon'>
                    <span data-feather='home'></span>
                    </span>
                    <span class='nav-link-text'>Dashboard</span>
                </div>
            </a>
        </div>";
}

//function to lock urn by it's current user & other can not edit urn info
function lockURNByMe($con)
{
	$data_array = [
					'user' => $_SESSION['user_ref_id'],
					'lead_id' => $_REQUEST['lead_id'],
					];

	insertData('working_on_lead_list',$data_array,$con);
}

//function to unlock urn by it's current user so that other can edit urn info
function unlockURNByMe($con)
{
	$query = "DELETE FROM working_on_lead_list WHERE user = '".$_SESSION['user_ref_id']."'";
	mysqli_query($con, $query);
}

//function to get current user of urn/lead if any
function getURNCurrentUser($con)
{
	if(isset($_REQUEST['lead_id']) && $_REQUEST['lead_id'])
	{
		if(getRowCount('lead_id',$_REQUEST['lead_id'],'working_on_lead_list',$con) > 0)
		{
			if(getFieldValue('user','lead_id',$_REQUEST['lead_id'],'working_on_lead_list',$con) == $_SESSION['user_ref_id'])
				return 1;
			else
				return 0;
		}
		else
		{
			lockURNByMe($con);
			return 1;
		}
	}
	else
	{
		if(getRowCount('user',$_SESSION['user_ref_id'],'working_on_lead_list',$con) > 0)
		{
			unlockURNByMe($con);
		}
	}
}

//function to display action_persorm list checkboxes
function displayActionPerformCheckboxes($con)
{
	$action_perform_list = getRowsData('action_perform_list',$con);

	while($action_perform = mysqli_fetch_assoc($action_perform_list))
	{
		echo "<div style='width:200px'><input type='checkbox' name='linked_action[]' class='form-check-input m-1' value='".$action_perform['id']."' onClick='countCheckboxChecked()'> <span class='fs-9 m-1'>".$action_perform['description']."</span></div>";
	}
}

//function to display linked action_persorm list checkboxes with email alert list
function displayActionPerformCheckboxesSelected($con)
{
	$linked_action_email_alert = getFieldValue('on_actions','id',$_REQUEST['trigger_id'],'email_alerts_setup',$con);
	$linked_action_email_alert_array = explode(',',$linked_action_email_alert);

	$action_perform_list = getRowsData('action_perform_list',$con);

	while($action_perform = mysqli_fetch_assoc($action_perform_list))
	{
		if(in_array($action_perform['id'],$linked_action_email_alert_array))
		echo "<div style='width:200px'><input type='checkbox' name='linked_action[]' class='form-check-input m-1' value='".$action_perform['id']."' checked onClick='countCheckboxChecked()'> <span class='fs-9 m-1'>".$action_perform['description']."</span></div>";
		else
		echo "<div style='width:200px'><input type='checkbox' name='linked_action[]' class='form-check-input m-1' value='".$action_perform['id']."' onClick='countCheckboxChecked()'> <span class='fs-9 m-1'>".$action_perform['description']."</span></div>";
	}
}

//create email history record
function createEmailHistory($type,$subject,$content,$recipients,$con)
{
	$email_history_data = [
							'type' => $type,
							'subject' => $subject,
							'content' => $content,
							'recipients' => $recipients,
							'sender' => "support@campus-abroad.co.in",
							'datentime' => strtotime("now"),
							];

	insertData("email_history",$email_history_data,$con);
}

//function to add more recipients from predifined email alert list
function setadditionalRecipients($action,$con)
{
	$recipients = "";
	if(getRowCount('description',$action,'action_perform_list',$con) > 0)
	{
		$action_id = getFieldValue('id','description',$action,'action_perform_list',$con);
		$email_alert_list = getRowsData("email_alerts_setup",$con);
		while($email_alert = mysqli_fetch_assoc($email_alert_list))
		{
			$action_id_array = explode(',',$email_alert['on_actions']);

			if(in_array($action_id,$action_id_array))
			{
				if($recipients == '')
					$recipients .= $email_alert['to_emails'];
				else
					$recipients .= ",".$email_alert['to_emails'];
			}
		}
		$recipients = implode(',',array_unique(explode(',',$recipients)));
	}
	return $recipients;
}

//create email history for new signup
function signupEmailHistory($signupType,$signupEmail,$signupName,$con)
{
	$recipients = $signupEmail;

	if(setadditionalRecipients($signupType,$con) != '')
	$recipients .= ','.setadditionalRecipients($signupType,$con);

	$type = "New ".$signupType." Alert";
	$subject = "Welcome ".$signupName." to Campus-Abroad";
	$content = "New ".$signupType." Alert";

	//send email
	sendMail($recipients,$subject,$content);

	createEmailHistory($type,$subject,$content,$recipients,$con);
}

//create email history for new withdrawal request/approval
function withdrawalEmailHistory($withdrawalType,$wallet_id,$con)
{
	$recipients = getWalletHolderEmail($wallet_id,$con);

	if(setadditionalRecipients($withdrawalType,$con) != '')
	$recipients .= ','.setadditionalRecipients($withdrawalType,$con);

	$type = $withdrawalType." Alert";
	$subject = $withdrawalType." Alert";
	$content = $withdrawalType." Alert";

	//send email
	sendMail($recipients,$subject,$content);

	createEmailHistory($type,$subject,$content,$recipients,$con);
}

//function to create email history for any type of urn updation
function urnupdationEmailHistory($updation_type,$lead_id,$lead_student_email,$con)
{
	$urn = getFieldValue('urn','id',$lead_id,'leads_details',$con);
	$type = $updation_type." Alert";
	$subject = "CA".$urn." ".$updation_type." Alert";
	$content = $updation_type." Alert";
	$recipients = $lead_student_email;

	if(setadditionalRecipients($updation_type,$con) != '')
	$recipients .= ','.setadditionalRecipients($updation_type,$con);

	//send email
	sendMail($recipients,$subject,$content);

	createEmailHistory($type,$subject,$content,$recipients,$con);
}

//function to create email history for normal status update for urn
function urnstatusEmailHistory($next_status_description,$lead_id,$lead_student_email,$con)
{
	$urn = getFieldValue('urn','id',$lead_id,'leads_details',$con);
	$recipients = $lead_student_email;
	$comparision_status_description_array = ['Applied','URN Approved','Visa Applied','Visa Approved','Fee Paid','URN Rejected','Visa Rejected','Deleted'];

	if(in_array($next_status_description,$comparision_status_description_array))
	{
		$type = "URN ".$next_status_description." Alert";
		$subject = "CA".$urn." ".$next_status_description." Alert";
		$content = $subject;
		$action = $next_status_description;
	}
	else
	{
		$type = "Status Updated Alert";
		$subject = "CA".$urn." Status Updated Alert";
		$content = "Status Updated Alert";
		$action = "Status Update";
	}	

	if(setadditionalRecipients($action,$con) != '')
	$recipients .= ','.setadditionalRecipients($action,$con);

	//send email
	sendMail($recipients,$subject,$content);

	createEmailHistory($type,$subject,$content,$recipients,$con);
}

//get wallet holder email
function getWalletHolderEmail($wallet_id,$con)
{
	$wallet_hoder_id = getFieldValue('holder_id','id',$wallet_id,'wallet_list',$con);
	$wallet_hoder_type = getFieldValue('holder_type','id',$wallet_id,'wallet_list',$con);

	if($wallet_hoder_type == 4)
	$wallet_holder_ref_id = "SA".$wallet_hoder_id;
	else if($wallet_hoder_type == 6)
	$wallet_holder_ref_id = "SP".$wallet_hoder_id;

	return getFieldValue('username','ref_id',$wallet_holder_ref_id,'login_detail',$con);
}

//function to send mail
function sendMail($recipients,$subject,$content)
{
	$headers = "From: support@campus-abroad.co.in";
	$recipients_array = explode(',',$recipients);
	foreach($recipients_array as $recipient)
	{
		mail($recipient, $subject, $content, $headers);
	}
}

//function to check each mandatory document uploaded or not for specific crn/customer
function checkDocumentUploadCount($urn,$uploaded_file_name,$con)
{
		$where_clause = " WHERE file_name LIKE '%".$uploaded_file_name."%' AND is_deleted = 0 AND urn = ".$urn;
		return getRowCountMultiCol($where_clause,'urn_document_upload_history',$con);
}

//function to check all mandatory documents uploaded or not for specific crn/customer
function checkMandatoryDocumentsUploadStatus($urn,$con)
{
	$upload_status_flag = 1;
	$where_con_array = [ 'is_required' => 1];
	
	$mandatory_documents_list = getRowsDataCon('document_list',$where_con_array,$con);
	while($mandatory_document = mysqli_fetch_assoc($mandatory_documents_list))
	{
		$where_clause = " WHERE file_name LIKE '%".$mandatory_document['uploaded_file_name']."%' AND is_deleted = 0 AND urn = ".$urn;
		if(getRowCountMultiCol($where_clause,'urn_document_upload_history',$con) == 0)
		$upload_status_flag = 0;
	}

	return $upload_status_flag;
}

//function to check requested user online/offline
function checkUserOnlineStatus($user_ref_id,$con)
{
    if(getRowCount('user_ref_id',$user_ref_id,'logged_user_list',$con))
    $user_logged_in_status = "<p class='fs-9 mb-0 me-2'> <span class='fa-solid fa-circle text-success fs-11 me-2'></span>Online</p>";
    else
    $user_logged_in_status = "<p class='fs-9 mb-0 me-2'> <span class='fa-solid fa-circle text-danger fs-11 me-2'></span>Offline</p>";

	return $user_logged_in_status;
}

?>